# -*- coding: utf-8 -*-
"""Movie_Recommendation_Cosine_Similarity_Beginner_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eS-Ii_qdh8pbI1v3wOfQNNkKQhZoAE_E

# 🎬 Movie Recommendation System using Cosine Similarity (Beginner)
A hard-coded 10-movie example using TF-IDF and Cosine Similarity.
"""

import pandas as pd

movies={
"Movie":["Avatar","Titanic","The Avengers","Iron Man","The Dark Knight","Interstellar","Inception","The Notebook","Joker","Doctor Strange"],
"Genre":[
"Action Adventure Sci-Fi",
"Romance Drama",
"Action Adventure Superhero",
"Action Superhero Sci-Fi",
"Action Crime Drama",
"Adventure Sci-Fi Drama",
"Action Sci-Fi Thriller",
"Romance Drama",
"Crime Drama Thriller",
"Action Fantasy Sci-Fi"
]
}

df=pd.DataFrame(movies)
df

"""## TF-IDF Vectorization"""

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer()
movie_vectors=tfidf.fit_transform(df["Genre"])
print(movie_vectors.shape)

"""## Cosine Similarity"""

from sklearn.metrics.pairwise import cosine_similarity

similarity=cosine_similarity(movie_vectors)

similarity_df=pd.DataFrame(similarity,index=df["Movie"],columns=df["Movie"])
similarity_df.round(2)

"""## Recommendation Function"""

def recommend(movie_name,n=5):
    scores=similarity_df[movie_name]
    return scores.sort_values(ascending=False).iloc[1:n+1]

recommend("Avatar")

recommend("Titanic")

"""## Similarity Heatmap"""

import matplotlib.pyplot as plt
import streamlit as st

fig, ax = plt.subplots()
im = ax.imshow(similarity_df.values, cmap="viridis")
fig.colorbar(im)
st.pyplot(fig)
plt.figure(figsize=(10,8))
plt.imshow(similarity_df,cmap='viridis')
plt.colorbar()
plt.xticks(range(len(df.Movie)),df.Movie,rotation=90)
plt.yticks(range(len(df.Movie)),df.Movie)
plt.title("Movie Similarity Matrix")
plt.show()
